name: Pull request into develop, main

on:
  pull_request:
    branches:
      - "develop"
      - "main"

jobs:
  install-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node modules
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Prettier
        run: npm run prettier:check

      - name: React Test
        run: npm run test

      - name: Build Project
        run: npm run build
